{
 "title": "hw02",
 "time": { "from": "2022-01-31T22:15:48.450Z", "to": "2022-01-31T22:30:38.380Z" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "kube_namespace_labels" } },
   {
    "name": "service_name",
    "query": {
     "query": "kube_service_info{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "db_name",
    "query": {
     "query": "kube_service_info{namespace=\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Common RPS by ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (exported_service) (increase(nginx_ingress_controller_requests{exported_service=\"$service_name\"}[1m]))/60",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "RPS by handler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (handler) (increase(app_request_total{service=\"$service_name\"}[1m])) / 60",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latency q0.5 (by ingress)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, exported_service)(increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service_name\"}[1m])) != 0)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency by 0.5q (handler)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, handler) (rate(app_response_time_seconds_bucket{service=\"$service_name\"}[1m])))",
     "legendFormat": "0.5q {{handler}}"
    }
   ]
  },
  {
   "title": "Latency q0.9 (by ingress)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, exported_service)(increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service_name\"}[1m])) != 0)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency by 0.9q (handler)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, handler) (rate(app_response_time_seconds_bucket{service=\"$service_name\"}[1m])))",
     "legendFormat": "0.9q {{handler}}"
    }
   ]
  },
  {
   "title": "Latency q0.99 (by ingress)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, exported_service)(increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service_name\"}[1m])) != 0)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency by 0.99q (handler)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, handler) (rate(app_response_time_seconds_bucket{service=\"$service_name\"}[1m])))",
     "legendFormat": "0.99q {{handler}}"
    }
   ]
  },
  {
   "title": "Latency max q (by ingress)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le, exported_service)(increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service_name\"}[1m])) != 0)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency by max q (handler)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le, handler) (rate(app_response_time_seconds_bucket{service=\"$service_name\"}[1m])))",
     "legendFormat": "max q {{handler}}"
    }
   ]
  },
  {
   "title": "Client Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (handler, status_code) (increase(app_response_time_seconds_count{service=\"$service_name\", status_code=~\"4..\"}[1m]))",
     "legendFormat": "{{status_code}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by (handler, status_code) (increase(app_response_time_seconds_count{service=\"$service_name\",status_code=~\"5..\"}[1m]))",
     "legendFormat": "{{status_code}} - {{handler}}"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"} * on(namespace,pod)\r\ngroup_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$service_name\", workload_type=\"deployment\"})\r\nby (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"} * on(namespace,pod)\r\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$service_name\", workload_type=\"deployment\"})\r\n\tby (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$db_name\"}[1m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(process_resident_memory_bytes{namespace=\"$namespace\", service=\"$db_name\"}[1m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "sum(increase(process_virtual_memory_bytes{namespace=\"$namespace\", service=\"$db_name\"}[1m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  }
 ]
}